In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Bengaluru_House_Data.csv")
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [3]:
data.drop(columns= ["area_type", "availability", "society"], inplace = True)

### Checking Null Values

In [4]:
data.isnull().sum()

location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

### Removing Null Values

In [5]:
data.dropna(inplace = True)

In [6]:
data.shape

(12710, 6)

In [7]:
data.location.value_counts()

location
Whitefield         514
Sarjapur  Road     372
Electronic City    300
Kanakpura Road     261
Thanisandra        231
                  ...
Gulakamale           1
Duddanahalli         1
Doddanakunte         1
Jogupalya            1
Abshot Layout        1
Name: count, Length: 1265, dtype: int64

## Data Cleaning

### For columns "Location"

In [8]:
# Removing space of locations
data["location"] = data["location"].apply(lambda x : x.strip())

In [9]:
location_stats = data.groupby("location")["location"].agg("count").sort_values(ascending = False)
location_stats

location
Whitefield                 515
Sarjapur  Road             372
Electronic City            302
Kanakpura Road             261
Thanisandra                234
                          ...
mvj engineering college      1
manyata tech park            1
manyata                      1
kg halli jalhalli west       1
kanakapura road              1
Name: location, Length: 1254, dtype: int64

In [10]:
location_less_than_10_entries = location_stats[location_stats <= 10]
location_less_than_10_entries

location
Basapura                   10
Gunjur Palya               10
Dairy Circle               10
HAL 2nd Stage              10
Kalkere                    10
                           ..
mvj engineering college     1
manyata tech park           1
manyata                     1
kg halli jalhalli west      1
kanakapura road             1
Name: location, Length: 1017, dtype: int64

In [11]:
# entries that have less than 10 is converted into "other"
data["location"] = data["location"].apply(lambda x:"other" if x in location_less_than_10_entries else x)

In [12]:
data["location"].value_counts()

location
other               2739
Whitefield           515
Sarjapur  Road       372
Electronic City      302
Kanakpura Road       261
                    ...
Marsur                11
Karuna Nagar          11
Prithvi Layout        11
Doddaballapur         11
Thyagaraja Nagar      11
Name: count, Length: 238, dtype: int64

In [13]:
data

                       location       size total_sqft  bath  balcony   price
0      Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                      Kothanur      2 BHK       1200   2.0      1.0   51.00
...                         ...        ...        ...   ...      ...     ...
13314         Green Glen Layout      3 BHK       1715   3.0      3.0  112.00
13315                Whitefield  5 Bedroom       3453   4.0      0.0  231.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0      1.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0      1.0  488.00
13319              Doddathoguru      1 BHK        550   1.0      1.0   17.00

[12710 rows x 6 columns]

### For column "Size"

In [14]:
data["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom', '8 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '11 Bedroom', '43 Bedroom',
       '14 BHK', '8 BHK', '12 Bedroom', '10 Bedroom', '13 BHK'],
      dtype=object)

In [15]:
data["bedrooms"] = data["size"].apply(lambda x:int(x.split(" ")[0]))
data

,location,size,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4
13319,Doddathoguru,1 BHK,550,1.0,1.0,17.00,1

### For column "Total sqft"

In [16]:
data.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [17]:
def clean(sqft):
    tokens = sqft.split("-")
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1]))/2
    else:
        try:
            return float(sqft)
        except:
            return None

In [18]:
data["total_sqft"] = data["total_sqft"].apply(clean)
data.total_sqft.unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [19]:
data.describe()

         total_sqft          bath       balcony         price      bedrooms
count  12668.000000  12710.000000  12710.000000  12710.000000  12710.000000
mean    1511.835167      2.617309      1.584343    106.060778      2.737136
std     1162.097276      1.226000      0.817287    131.766089      1.205097
min        5.000000      1.000000      0.000000      8.000000      1.000000
25%     1100.000000      2.000000      1.000000     49.030000      2.000000
50%     1260.000000      2.000000      2.000000     70.000000      3.000000
75%     1640.000000      3.000000      2.000000    115.000000      3.000000
max    52272.000000     40.000000      3.000000   2912.000000     43.000000

In [20]:
data.isnull().sum()

location       0
size           0
total_sqft    42
bath           0
balcony        0
price          0
bedrooms       0
dtype: int64

In [21]:
data.dropna(inplace = True)

In [22]:
data

,location,size,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4
13319,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1

In [23]:
data["sqft_per_bedroom"] = data["total_sqft"]/ data["bedrooms"]
data.head()

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bedroom
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.0
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.0
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.0
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.0
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.0

In [24]:
data.sqft_per_bedroom.describe()

count    12668.000000
mean       570.060291
std        380.298999
min          0.714286
25%        473.333333
50%        550.000000
75%        622.500000
max      26136.000000
Name: sqft_per_bedroom, dtype: float64

since here minimun value is 0 which is invalid ..coz no rooms size can be 0 sqft

In [25]:
data = data[data["sqft_per_bedroom"]>= 300]
data

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bedroom
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000
...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000
13319,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000

In [26]:
data.sqft_per_bedroom.describe()

count    12013.000000
mean       590.451121
std        379.862312
min        300.000000
25%        490.000000
50%        560.000000
75%        626.000000
max      26136.000000
Name: sqft_per_bedroom, dtype: float64

In [27]:
data["price_per_sqft"] = round(data["price"]*100000/data["total_sqft"],2)
data

C:\Users\ashit\AppData\Local\Temp\ipykernel_7024\3579058317.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["price_per_sqft"] = round(data["price"]*100000/data["total_sqft"],2)

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bedroom,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000,3699.81
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000,4615.38
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000,4305.56
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000,6245.89
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000,4250.00
...,...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667,6530.61
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000,6689.83
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000,5258.55
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000,10407.34
13319,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000,3090.91

In [28]:
data["price_per_sqft"].describe()

count     12013.000000
mean       6206.082361
std        3985.518849
min         267.830000
25%        4199.360000
50%        5252.530000
75%        6823.530000
max      176470.590000
Name: price_per_sqft, dtype: float64

In [29]:
data = data[data["price_per_sqft"] >= 2000]
data

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bedroom,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000,3699.81
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000,4615.38
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000,4305.56
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000,6245.89
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000,4250.00
...,...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667,6530.61
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000,6689.83
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000,5258.55
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000,10407.34
13319,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000,3090.91

In [30]:
data["price_per_sqft"].describe()

count     11985.000000
mean       6217.539640
std        3983.028298
min        2000.000000
25%        4200.000000
50%        5263.160000
75%        6832.860000
max      176470.590000
Name: price_per_sqft, dtype: float64

In [31]:
data.drop(columns = ["size", "sqft_per_bedroom", "price_per_sqft"], axis = 1, inplace = True) # we create these columns to remove outliers..so now we drop them.. 
data

C:\Users\ashit\AppData\Local\Temp\ipykernel_7024\1040952984.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns = ["size", "sqft_per_bedroom", "price_per_sqft"], axis = 1, inplace = True) # we create these columns to remove outliers..so now we drop them..

                       location  total_sqft  bath  balcony   price  bedrooms
0      Electronic City Phase II      1056.0   2.0      1.0   39.07         2
1              Chikka Tirupathi      2600.0   5.0      3.0  120.00         4
2                   Uttarahalli      1440.0   2.0      3.0   62.00         3
3            Lingadheeranahalli      1521.0   3.0      1.0   95.00         3
4                      Kothanur      1200.0   2.0      1.0   51.00         2
...                         ...         ...   ...      ...     ...       ...
13314         Green Glen Layout      1715.0   3.0      3.0  112.00         3
13315                Whitefield      3453.0   4.0      0.0  231.00         5
13317     Raja Rajeshwari Nagar      1141.0   2.0      1.0   60.00         2
13318           Padmanabhanagar      4689.0   4.0      1.0  488.00         4
13319              Doddathoguru       550.0   1.0      1.0   17.00         1

[11985 rows x 6 columns]

In [32]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

In [33]:
ohe = OneHotEncoder(sparse_output=False)

sparse_output=False: By default, OneHotEncoder outputs a sparse matrix, which is a memory-efficient way to store data that is mostly zeros. Setting this to False tells the encoder to output a regular, dense NumPy array, which is often easier to look at and work with directly.

In [34]:
ohe

OneHotEncoder(sparse_output=False)

In [35]:
# One-hot encode the 'location' column and keep all other columns.
# Create a preprocessor to apply one-hot encoding to the 'location' column, passing through the rest.
col_trans = make_column_transformer((ohe, ["location"]), remainder="passthrough")

(ohe, ["location"]): This is a tuple that acts as an instruction. It tells the ColumnTransformer: "Take the ohe object you created earlier and apply it only to the column named "location"."

remainder="passthrough": This is a crucial argument. It answers the question, "What should I do with all the other columns that you didn't tell me to transform (i.e., every column except "location")?" The value "passthrough" means: "Just leave them as they are and carry them over to the final output without any changes." The other common option is "drop", which would discard them entirely.

In [36]:
lr = LinearRegression()
ss = StandardScaler()

In [37]:
model = make_pipeline(col_trans, ss, lr)

In [38]:
#spliting data into input and output variable
x = data.drop(columns = "price") # Input
y = data["price"] # Output

In [39]:
# Spliting in training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [40]:
model.fit(x_train, y_train)

C:\Users\ashit\AppData\Roaming\Python\Python312\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [41]:
model.score(x_train, y_train)*100

62.65682180781369

In [42]:
model.score(x_test, y_test)*100

67.42344251447545

In [43]:
input = pd.DataFrame([["Electronic City Phase II", 2000.0, 3.0, 2.0, 3]], columns = ["location", "total_sqft", "bath","balcony", "bedrooms"])

In [44]:
model.predict(input)

array([134.09939617])

In [45]:
import pickle as pk

In [46]:
pk.dump(model, open("House Price Prediction.pkl","wb"))

In [47]:
data.to_csv("Cleaned_data.csv")